language: node_js

node_js: "13"

branches:
  only:
    - master

addons:
  sonarcloud:
    organization: duraes-antonio-github

install:
  - yarn install

script:
  - yarn run test
  - sonar-scanner
