language: node_js

node_js: "13"

branches:
  only:
    - master

addons:
  sonarcloud:
    organization: "duraes-antonio-github"
    token:
      secure: "fT8F9SYFqb7ykTZDgioDfgpjX2sgu5SQ1QQE1ebz/5qM8WMOq0SIHBs6ywG2MWIqjQWVAesLEIHXYRk3nA5KCRqvzY9hZ33Hf52lOkzTTLI0GflnWJHW1eJ1CT/GNP7OFxPN+5AUwwIW6WHyV6HE3KhJepLaVj1FsAvdHiSdpukzIPVprzS44jdfyZrnI51qIJ7zi3b1CufC7vRaURgqF+qO8IiTJhlLOKTzpQzTO6IMoNo/q6riHEjwUoumOGztxWrw1bGnpO2d8vF2c4MLHITMfdt79FrjdFiWSDFyUmkgTrgCvYH6v+hKdN45638Vyvh7DaQNPq0kkWj8heRLLfLO0kbFMG19xE/B6RVDu3rd9hPqfNbSEjT3OtRMHWOVBSZdQfRsDutS0vIvVLRF7V66OhZqPXNLZEfh9yj2kx1T1f/WRhaMkB6EepgfuKB3MpahAPobD341PxNH74giYGb91Qi7KTeSOw4aqt4gCK4eLsNfVtGkwu3SBxjQg+NGlyKIujD+akrr4inSI8wIpCsJtRCk6GwRvnOw+Rj41EP/tybTIxQ8SgGt1xaGWwGjKD//FxRM000hWDz4NO9kA0v5Xmsu+hZqcNHI+3EiAsRigW3JZTFUVCkJXHP2VD1+U7hfh/9PU/G3SQOqOfN8WLvhhYsmRb5SpOFZZ8NyqgE="

install:
  - yarn install

script:
  - yarn run test
  - sonar-scanner

deploy:
  provider: heroku
  api_key:
    secure: "SYgj05A7YUOJVS5/8kpNyDuSEEteeSh6hOl5fLNZkfar2V2KmFj4ChDf/eUc8OMzPMRF+662BlCO1PBysEx0awsAY+7mN+ZllOQ1Wf+y8ZTfqHOGIDTAEAS84JNUqyJb9de7KCZKp0xj0/6LRMKZQTcqMLhNULgv4oiKq5sql8ViKb+Kvpt0M2h5sUHwLyWCW6KmR/N1Vh4BidWdI/xwCkDB+kR2yiqvLwECe578UCelUvSn+UzJczTYrUMBFr30wcsPtC1+hZsrlHJoNd49CZhv3OYZnGD/xpokvr/XfaSLOPin7j8NCsxpEKhKi40faBnJy+G9jFsTOi2BvV3VxEOoxJDgZzcCGUdmvVQhJTJEdVe1HsPGsKSZZ1A17//As2TvTTxuJ9Qf5WX9C3hUfR6NEH1pPtAlAzP4yNwNjUT5vkcAPoSdxnPMNtUw9E1+g/y7S3tuembXJ/+/FFAc2P/HQVUAWmqt5++eTf//7uvMt4Hv9Nzep7z37eQ6bw87QTx1mqMdpI8LozUeE3sFV78ssTm6sHdqMePm4aoU3zbO493TEl0+OSxIQTBVwKQVVEUUVE+m4iTEyA+bGfKaxCMS7+q7Tn2rk1q8TfX5A9R1dZbLjSbWeQonvUJm8SLGu+z8HGzuXNux2y5P9dScTbJtZbTzHxDH8HzqAoJGgAE="
  app: ce2020-backend


