language: node_js

node_js: "13"

branches:
  only:
    - master

addons:
  sonarcloud:
    organization: duraes-antonio-github
    secure:
      token: ${SONAR_TOKEN}

install:
  - yarn install

script:
  - yarn test
  - sonar-scanner
